/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-115062-g5bc3b7f-Reino"
#endif /* AVUTIL_FFVERSION_H */
